/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTelegramRouteImport } from './routes/dashboard.telegram'
import { Route as DashboardSystemRouteImport } from './routes/dashboard.system'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardBiodiversityRouteImport } from './routes/dashboard.biodiversity'
import { Route as DashboardAudioRouteImport } from './routes/dashboard.audio'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramRoute = DashboardTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemRoute = DashboardSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBiodiversityRoute = DashboardBiodiversityRouteImport.update({
  id: '/biodiversity',
  path: '/biodiversity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAudioRoute = DashboardAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/biodiversity': typeof DashboardBiodiversityRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/biodiversity': typeof DashboardBiodiversityRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/biodiversity': typeof DashboardBiodiversityRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audio'
    | '/dashboard/biodiversity'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/telegram'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audio'
    | '/dashboard/biodiversity'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/telegram'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audio'
    | '/dashboard/biodiversity'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/system'
    | '/dashboard/telegram'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram': {
      id: '/dashboard/telegram'
      path: '/telegram'
      fullPath: '/dashboard/telegram'
      preLoaderRoute: typeof DashboardTelegramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system': {
      id: '/dashboard/system'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof DashboardSystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/biodiversity': {
      id: '/dashboard/biodiversity'
      path: '/biodiversity'
      fullPath: '/dashboard/biodiversity'
      preLoaderRoute: typeof DashboardBiodiversityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audio': {
      id: '/dashboard/audio'
      path: '/audio'
      fullPath: '/dashboard/audio'
      preLoaderRoute: typeof DashboardAudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAudioRoute: typeof DashboardAudioRoute
  DashboardBiodiversityRoute: typeof DashboardBiodiversityRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSystemRoute: typeof DashboardSystemRoute
  DashboardTelegramRoute: typeof DashboardTelegramRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAudioRoute: DashboardAudioRoute,
  DashboardBiodiversityRoute: DashboardBiodiversityRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSystemRoute: DashboardSystemRoute,
  DashboardTelegramRoute: DashboardTelegramRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
